import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: 'var(--color-surface)',
        "surface-dim": 'var(--color-surface-dim)',
        "surface-bright": 'var(--color-surface-bright)',
        "surface-container-lowest": 'var(--color-surface-container-lowest)',
        "surface-container-low": 'var(--color-surface-container-low)',
        "surface-container": 'var(--color-surface-container)',
        "surface-container-high": 'var(--color-surface-container-high)',
        "surface-container-highest": 'var(--color-surface-container-highest)',
        "on-surface": 'var(--color-on-surface)',
        "on-surface-variant": 'var(--color-on-surface-variant)',
        "inverse-surface": 'var(--color-inverse-surface)',
        "inverse-on-surface": 'var(--color-inverse-on-surface)',
        outline: 'var(--color-outline)',
        "outline-variant": 'var(--color-outline-variant)',
        "surface-tint": 'var(--color-surface-tint)',
        primary: 'var(--color-primary)',
        "on-primary": 'var(--color-on-primary)',
        "primary-container": 'var(--color-primary-container)',
        "on-primary-container": 'var(--color-on-primary-container)',
        "inverse-primary": 'var(--color-inverse-primary)',
        secondary: 'var(--color-secondary)',
        "on-secondary": 'var(--color-on-secondary)',
        "secondary-container": 'var(--color-secondary-container)',
        "on-secondary-container": 'var(--color-on-secondary-container)',
        tertiary: 'var(--color-tertiary)',
        "on-tertiary": 'var(--color-on-tertiary)',
        "tertiary-container": 'var(--color-tertiary-container)',
        "on-tertiary-container": 'var(--color-on-tertiary-container)',
        error: 'var(--color-error)',
        "on-error": 'var(--color-on-error)',
        "error-container": 'var(--color-error-container)',
        "on-error-container": 'var(--color-on-error-container)',
        "primary-fixed": 'var(--color-primary-fixed)',
        "primary-fixed-dim": 'var(--color-primary-fixed-dim)',
        "on-primary-fixed": 'var(--color-on-primary-fixed)',
        "on-primary-fixed-variant": 'var(--color-on-primary-fixed-variant)',
        "secondary-fixed": 'var(--color-secondary-fixed)',
        "secondary-fixed-dim": 'var(--color-secondary-fixed-dim)',
        "on-secondary-fixed": 'var(--color-on-secondary-fixed)',
        "on-secondary-fixed-variant": 'var(--color-on-secondary-fixed-variant)',
        "tertiary-fixed": 'var(--color-tertiary-fixed)',
        "tertiary-fixed-dim": 'var(--color-tertiary-fixed-dim)',
        "on-tertiary-fixed": 'var(--color-on-tertiary-fixed)',
        "on-tertiary-fixed-variant": 'var(--color-on-tertiary-fixed-variant)',
        background: 'var(--color-background)',
        "on-background": 'var(--color-on-background)',
        "surface-variant": 'var(--color-surface-variant)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',
        "bg-page": 'var(--color-bg-page)',
        "bg-card": 'var(--color-bg-card)',
        "border-subtle": 'var(--color-border-subtle)',

        // Extended primary scale
        "primary-50": "var(--color-primary-50)",
        "primary-100": "var(--color-primary-100)",
        "primary-200": "var(--color-primary-200)",
        "primary-300": "var(--color-primary-300)",
        "primary-400": "var(--color-primary-400)",
        "primary-500": "var(--color-primary-500)",
        "primary-600": "var(--color-primary-600)",
        "primary-700": "var(--color-primary-700)",
        "primary-800": "var(--color-primary-800)",
        "primary-900": "var(--color-primary-900)",

        // Neutral scale
        "neutral-50": "var(--color-neutral-50)",
        "neutral-100": "var(--color-neutral-100)",
        "neutral-200": "var(--color-neutral-200)",
        "neutral-300": "var(--color-neutral-300)",
        "neutral-400": "var(--color-neutral-400)",
        "neutral-500": "var(--color-neutral-500)",
        "neutral-600": "var(--color-neutral-600)",
        "neutral-700": "var(--color-neutral-700)",
        "neutral-800": "var(--color-neutral-800)",
        "neutral-900": "var(--color-neutral-900)",
      },
      fontFamily: {
        sans: ["var(--font-family-primary)", "sans-serif"],
        mono: ["var(--font-family-mono)", "monospace"],
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      borderRadius: {
        "sm": "0.25rem",
        DEFAULT: "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      }
    },
  },
  plugins: [],
};

export default config;
